# Generated by Django 3.1.6 on 2021-04-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='hari_jam',
        ),
        migrations.AddField(
            model_name='documents',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
