# Generated by Django 3.1.6 on 2021-06-21 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='date_input',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 8, 34, 19, 604792), null=True),
        ),
        migrations.AlterField(
            model_name='documentsddpr',
            name='Tanggal',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 8, 34, 19, 605790), null=True, verbose_name='Tanggal '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='Tanggal',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 8, 34, 19, 605309), null=True, verbose_name='Tanggal '),
        ),
    ]
