# Generated by Django 3.1.6 on 2021-06-10 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithms', '0002_auto_20210430_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsPageRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=500, null=True)),
                ('Tanggal', models.DateTimeField(default=datetime.datetime(2021, 6, 10, 16, 5, 18, 448439), null=True)),
                ('Wilayah', models.CharField(choices=[('east_java', 'Jawa Timur'), ('central_java', 'Jawa Tengah')], default='east_java', max_length=12)),
                ('File_PDB_Regional', models.FileField(null=True, upload_to='')),
                ('File_Jumlah_Penduduk_Laki_Laki', models.FileField(null=True, upload_to='')),
                ('File_Tingkat_Pengangguran', models.FileField(null=True, upload_to='')),
                ('File_Jumlah_Kejahatan', models.FileField(null=True, upload_to='')),
                ('File_Kepadatan_Penduduk', models.FileField(null=True, upload_to='')),
                ('File_Angka_Melek_Huruf', models.FileField(null=True, upload_to='')),
                ('File_Rata_Rata_Pendapatan_Pekerja_Informal', models.FileField(null=True, upload_to='')),
                ('File_Upah_Minimum_Regional', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='documents',
            name='date_input',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 16, 5, 18, 447934), null=True),
        ),
    ]
