# Generated by Django 3.1.6 on 2021-06-13 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithms', '0004_auto_20210613_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='date_input',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 11, 20, 16, 27896), null=True),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_GDP',
            field=models.FileField(null=True, upload_to='', verbose_name='File PDB Regional '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_MIN',
            field=models.FileField(null=True, upload_to='', verbose_name='File Upah Minimum Regional '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='Nama',
            field=models.CharField(max_length=100, null=True, verbose_name='Nama '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='Tanggal',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 11, 20, 16, 28350), null=True, verbose_name='Tanggal '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='Wilayah',
            field=models.CharField(choices=[('east_java', 'Jawa Timur'), ('central_java', 'Jawa Tengah'), ('bali', 'Bali')], default='east_java', max_length=12, verbose_name='Wilayah '),
        ),
    ]
