# Generated by Django 3.1.6 on 2021-06-13 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithms', '0005_auto_20210613_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='date_input',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 1, 4, 9, 405574), null=True),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_CRIM',
            field=models.FileField(null=True, upload_to='uploads/2021/6/14/', verbose_name='File Jumlah Kejahatan '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_Cases',
            field=models.FileField(null=True, upload_to='uploads/2021/6/14/', verbose_name='File Jumlah Kasus Terkonfirmasi Covid-19 '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_DENS',
            field=models.FileField(null=True, upload_to='uploads/2021/6/14/', verbose_name='File Kepadatan Penduduk '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_GDP',
            field=models.FileField(null=True, upload_to='uploads/2021/6/14/', verbose_name='File PDB Regional '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_INF',
            field=models.FileField(null=True, upload_to='uploads/2021/6/14/', verbose_name='File Rata-Rata Pendapatan Pekerja Informal '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_LIT',
            field=models.FileField(null=True, upload_to='uploads/2021/6/14/', verbose_name='File Angka Melek Huruf '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_MAN',
            field=models.FileField(null=True, upload_to='uploads/2021/6/14/', verbose_name='File Jumlah Penduduk Laki-Laki '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_MIN',
            field=models.FileField(null=True, upload_to='uploads/2021/6/14/', verbose_name='File Upah Minimum Regional '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_UNEM',
            field=models.FileField(null=True, upload_to='uploads/2021/6/14/', verbose_name='File Tingkat Pengangguran '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='Tanggal',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 1, 4, 9, 406088), null=True, verbose_name='Tanggal '),
        ),
    ]
