# Generated by Django 3.1.6 on 2021-06-14 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithms', '0006_auto_20210614_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='date_input',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 20, 25, 54, 964161), null=True),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='Tanggal',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 20, 25, 54, 964836), null=True, verbose_name='Tanggal '),
        ),
    ]
