# Generated by Django 3.1.6 on 2021-06-18 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithms', '0007_auto_20210614_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsDDPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=100, null=True, verbose_name='Nama ')),
                ('Tanggal', models.DateTimeField(default=datetime.datetime(2021, 6, 18, 15, 7, 6, 767735), null=True, verbose_name='Tanggal ')),
                ('File_Jarak', models.FileField(null=True, upload_to='uploads/2021/6/18/', verbose_name='File OD Matrix Beserta Jarak Antar Stasiun ')),
                ('File_Kasus_Stasiun', models.FileField(null=True, upload_to='uploads/2021/6/18/', verbose_name='File Jumlah Kasus Terkonfirmasi Covid-19 Per Stasiun ')),
            ],
        ),
        migrations.AlterField(
            model_name='documents',
            name='date_input',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 15, 7, 6, 766466), null=True),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_CRIM',
            field=models.FileField(null=True, upload_to='uploads/2021/6/18/', verbose_name='File Jumlah Kejahatan '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_Cases',
            field=models.FileField(null=True, upload_to='uploads/2021/6/18/', verbose_name='File Jumlah Kasus Terkonfirmasi Covid-19 '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_DENS',
            field=models.FileField(null=True, upload_to='uploads/2021/6/18/', verbose_name='File Kepadatan Penduduk '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_GDP',
            field=models.FileField(null=True, upload_to='uploads/2021/6/18/', verbose_name='File PDB Regional '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_INF',
            field=models.FileField(null=True, upload_to='uploads/2021/6/18/', verbose_name='File Rata-Rata Pendapatan Pekerja Informal '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_LIT',
            field=models.FileField(null=True, upload_to='uploads/2021/6/18/', verbose_name='File Angka Melek Huruf '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_MAN',
            field=models.FileField(null=True, upload_to='uploads/2021/6/18/', verbose_name='File Jumlah Penduduk Laki-Laki '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_MIN',
            field=models.FileField(null=True, upload_to='uploads/2021/6/18/', verbose_name='File Upah Minimum Regional '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='File_UNEM',
            field=models.FileField(null=True, upload_to='uploads/2021/6/18/', verbose_name='File Tingkat Pengangguran '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='Tanggal',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 15, 7, 6, 767120), null=True, verbose_name='Tanggal '),
        ),
    ]
