# Generated by Django 3.1.6 on 2021-06-19 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithms', '0009_auto_20210619_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='date_input',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 16, 57, 31, 271942), null=True),
        ),
        migrations.AlterField(
            model_name='documentsddpr',
            name='Tanggal',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 16, 57, 31, 274191), null=True, verbose_name='Tanggal '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='Tanggal',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 16, 57, 31, 272952), null=True, verbose_name='Tanggal '),
        ),
    ]
