# Generated by Django 3.1.6 on 2021-06-19 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithms', '0010_auto_20210619_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='date_input',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 21, 27, 35, 761826), null=True),
        ),
        migrations.AlterField(
            model_name='documentsddpr',
            name='Tanggal',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 21, 27, 35, 763343), null=True, verbose_name='Tanggal '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='Tanggal',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 21, 27, 35, 762513), null=True, verbose_name='Tanggal '),
        ),
    ]
