# Generated by Django 3.1.6 on 2021-06-19 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithms', '0011_auto_20210619_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='date_input',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 21, 35, 19, 275617), null=True),
        ),
        migrations.AlterField(
            model_name='documentsddpr',
            name='Tanggal',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 21, 35, 19, 277116), null=True, verbose_name='Tanggal '),
        ),
        migrations.AlterField(
            model_name='documentspagerank',
            name='Tanggal',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 21, 35, 19, 276301), null=True, verbose_name='Tanggal '),
        ),
    ]
